#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotLeaveRequest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="testL3")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert_Employee(_Employee instance);
    partial void Update_Employee(_Employee instance);
    partial void Delete_Employee(_Employee instance);
    partial void Insert_EmployeeEmergeLeave(_EmployeeEmergeLeave instance);
    partial void Update_EmployeeEmergeLeave(_EmployeeEmergeLeave instance);
    partial void Delete_EmployeeEmergeLeave(_EmployeeEmergeLeave instance);
    partial void Insert_AttendanceCode(_AttendanceCode instance);
    partial void Update_AttendanceCode(_AttendanceCode instance);
    partial void Delete_AttendanceCode(_AttendanceCode instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["testL3ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_Employee> _Employees
		{
			get
			{
				return this.GetTable<_Employee>();
			}
		}
		
		public System.Data.Linq.Table<_EmployeeEmergeLeave> _EmployeeEmergeLeaves
		{
			get
			{
				return this.GetTable<_EmployeeEmergeLeave>();
			}
		}
		
		public System.Data.Linq.Table<_AttendanceCode> _AttendanceCodes
		{
			get
			{
				return this.GetTable<_AttendanceCode>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_BloodType", IsComposable=true)]
		public string fn_BloodType([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Int")] System.Nullable<int> type)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), type).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_FullName", IsComposable=true)]
		public string fn_FullName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MiddleName", DbType="VarChar(50)")] string middleName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(50)")] string lastName)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstName, middleName, lastName).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Gender", IsComposable=true)]
		public string fn_Gender([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Int")] System.Nullable<int> type)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), type).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Religion", IsComposable=true)]
		public string fn_Religion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Int")] System.Nullable<int> type)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), type).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Employee]")]
	public partial class _Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Number;
		
		private string _Barcode;
		
		private string _FullName;
		
		private System.Data.Linq.Binary _UnitDrawing;
		
		private string _Address;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Phone;
		
		private string _HandPhone;
		
		private string _Email;
		
		private System.Nullable<int> _Religion;
		
		private System.Nullable<int> _Gender;
		
		private string _Hobby;
		
		private System.Nullable<int> _MaritalStatus;
		
		private System.Nullable<int> _EmployeeStatus;
		
		private System.Nullable<int> _OverTimeStatus;
		
		private System.Nullable<System.Guid> _OverTimeGroupId;
		
		private System.Nullable<System.Guid> _BaseRateGroupId;
		
		private string _PointOfHire;
		
		private string _NPWP;
		
		private System.Nullable<System.DateTime> _NPWPDate;
		
		private System.Nullable<bool> _fNPWP;
		
		private System.Nullable<decimal> _AutoNumber;
		
		private string _Contact1;
		
		private string _Contact2;
		
		private string _Contact;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private string _PlaceOfBirth;
		
		private string _Description;
		
		private System.Nullable<System.Guid> _BranchId;
		
		private System.Nullable<System.Guid> _JobId;
		
		private System.Nullable<System.Guid> _OrganizationId;
		
		private System.Nullable<System.Guid> _ClassId;
		
		private System.Nullable<int> _BloodType;
		
		private string _Height;
		
		private string _Weight;
		
		private string _Nationality;
		
		private string _Ethnic;
		
		private string _IdNumber;
		
		private System.Nullable<System.DateTime> _IdNumberExpire;
		
		private string _DrivingLicenseA;
		
		private System.Nullable<System.DateTime> _DrivingLicenseAExpire;
		
		private string _DrivingLicenseB;
		
		private System.Nullable<System.DateTime> _DrivingLicenseBExpire;
		
		private string _DrivingLicenseC;
		
		private System.Nullable<System.DateTime> _DrivingLicenseCExpire;
		
		private string _DrivingLicenseB1;
		
		private System.Nullable<System.DateTime> _DrivingLicenseB1Expire;
		
		private string _DrivingLicenseB2;
		
		private System.Nullable<System.DateTime> _DrivingLicenseB2Expire;
		
		private System.Nullable<int> _PaymentType;
		
		private System.Nullable<System.DateTime> _EffectiveDate;
		
		private System.Nullable<System.DateTime> _ResignDate;
		
		private System.Nullable<System.DateTime> _JoinDate;
		
		private System.Nullable<System.DateTime> _EndEffectiveDate;
		
		private System.Nullable<int> _BasicSalaryType;
		
		private System.Nullable<decimal> _BasicSalary;
		
		private System.Nullable<System.Guid> _BasicSalaryComponentId;
		
		private System.Nullable<int> _TaxStatus;
		
		private System.Nullable<System.Guid> _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.Guid> _ModifiedBy;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private System.Nullable<bool> _fJPK;
		
		private System.Nullable<System.DateTime> _JPKDate;
		
		private System.Nullable<bool> _fPensionFund;
		
		private string _PensionFundNo;
		
		private System.Nullable<System.DateTime> _PensionFundDate;
		
		private string _PensionNo;
		
		private System.Nullable<bool> _fPension;
		
		private System.Nullable<int> _JKK;
		
		private string _JamSosTekNo;
		
		private System.Nullable<System.DateTime> _JamSosTekDate;
		
		private System.Nullable<bool> _fJamSosTek;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _ClaimTaxType;
		
		private System.Nullable<int> _LeaveCompensationTaxType;
		
		private System.Nullable<int> _SourceType;
		
		private System.Nullable<bool> _FlexibleTime;
		
		private System.Nullable<int> _JamSosTekTaxType;
		
		private string _UserId;
		
		private System.Nullable<int> _EmployeeTaxStatus;
		
		private string _EBasicSalary;
		
		private System.Nullable<int> _EStatus;
		
		private string _Password;
		
		private System.Data.Linq.Binary _SignatureDrawing;
		
		private System.Nullable<bool> _ResetPassword;
		
		private System.Nullable<decimal> _BegRSalaryNetto;
		
		private System.Nullable<decimal> _BegRPPH21;
		
		private string _PhoneExtension;
		
		private System.Nullable<System.Guid> _RehireEmployeeId;
		
		private System.Nullable<System.DateTime> _PensionDate;
		
		private System.Nullable<System.Guid> _NPPJamsostekId;
		
		private System.Nullable<int> _fJHT;
		
		private System.Nullable<System.DateTime> _PayrollLastRunDate;
		
		private System.Nullable<System.DateTime> _AttendanceLastRunDate;
		
		private System.Nullable<System.DateTime> _HumanResourcesLastRunDate;
		
		private System.Nullable<bool> _fBPJS;
		
		private System.Nullable<System.DateTime> _BPJSDate;
		
		private string _BPJSNo;
		
		private System.Nullable<System.DateTime> _PaymentStartDate;
		
		private System.Nullable<int> _BPJSFamily;
		
		private System.Nullable<bool> _fForeign;
		
		private System.Nullable<int> _TaxCountryCode;
		
		private string _KITAS;
		
		private System.Nullable<System.DateTime> _KITASExpire;
		
		private string _Passport;
		
		private System.Nullable<System.DateTime> _PassportExpire;
		
		private System.Nullable<bool> _fJP;
		
		private System.Nullable<System.DateTime> _JPDate;
		
		private string _FamilyCardNumber;
		
		private System.Nullable<System.DateTime> _FamilyCardNumberExpire;
		
		private System.Nullable<System.DateTime> _JoinDateRehire;
		
		private System.Nullable<System.DateTime> _FirstEmploymentDate;
		
		private System.Nullable<int> _HireType;
		
		private string _City;
		
		private string _City1;
		
		private string _City2;
		
		private string _ZipCode;
		
		private string _ZipCode1;
		
		private string _ZipCode2;
		
		private string _EmailLinkage;
		
		private string _EmailPayslip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnUnitDrawingChanging(System.Data.Linq.Binary value);
    partial void OnUnitDrawingChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnHandPhoneChanging(string value);
    partial void OnHandPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnReligionChanging(System.Nullable<int> value);
    partial void OnReligionChanged();
    partial void OnGenderChanging(System.Nullable<int> value);
    partial void OnGenderChanged();
    partial void OnHobbyChanging(string value);
    partial void OnHobbyChanged();
    partial void OnMaritalStatusChanging(System.Nullable<int> value);
    partial void OnMaritalStatusChanged();
    partial void OnEmployeeStatusChanging(System.Nullable<int> value);
    partial void OnEmployeeStatusChanged();
    partial void OnOverTimeStatusChanging(System.Nullable<int> value);
    partial void OnOverTimeStatusChanged();
    partial void OnOverTimeGroupIdChanging(System.Nullable<System.Guid> value);
    partial void OnOverTimeGroupIdChanged();
    partial void OnBaseRateGroupIdChanging(System.Nullable<System.Guid> value);
    partial void OnBaseRateGroupIdChanged();
    partial void OnPointOfHireChanging(string value);
    partial void OnPointOfHireChanged();
    partial void OnNPWPChanging(string value);
    partial void OnNPWPChanged();
    partial void OnNPWPDateChanging(System.Nullable<System.DateTime> value);
    partial void OnNPWPDateChanged();
    partial void OnfNPWPChanging(System.Nullable<bool> value);
    partial void OnfNPWPChanged();
    partial void OnAutoNumberChanging(System.Nullable<decimal> value);
    partial void OnAutoNumberChanged();
    partial void OnContact1Changing(string value);
    partial void OnContact1Changed();
    partial void OnContact2Changing(string value);
    partial void OnContact2Changed();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnPlaceOfBirthChanging(string value);
    partial void OnPlaceOfBirthChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnBranchIdChanging(System.Nullable<System.Guid> value);
    partial void OnBranchIdChanged();
    partial void OnJobIdChanging(System.Nullable<System.Guid> value);
    partial void OnJobIdChanged();
    partial void OnOrganizationIdChanging(System.Nullable<System.Guid> value);
    partial void OnOrganizationIdChanged();
    partial void OnClassIdChanging(System.Nullable<System.Guid> value);
    partial void OnClassIdChanged();
    partial void OnBloodTypeChanging(System.Nullable<int> value);
    partial void OnBloodTypeChanged();
    partial void OnHeightChanging(string value);
    partial void OnHeightChanged();
    partial void OnWeightChanging(string value);
    partial void OnWeightChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnEthnicChanging(string value);
    partial void OnEthnicChanged();
    partial void OnIdNumberChanging(string value);
    partial void OnIdNumberChanged();
    partial void OnIdNumberExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnIdNumberExpireChanged();
    partial void OnDrivingLicenseAChanging(string value);
    partial void OnDrivingLicenseAChanged();
    partial void OnDrivingLicenseAExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnDrivingLicenseAExpireChanged();
    partial void OnDrivingLicenseBChanging(string value);
    partial void OnDrivingLicenseBChanged();
    partial void OnDrivingLicenseBExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnDrivingLicenseBExpireChanged();
    partial void OnDrivingLicenseCChanging(string value);
    partial void OnDrivingLicenseCChanged();
    partial void OnDrivingLicenseCExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnDrivingLicenseCExpireChanged();
    partial void OnDrivingLicenseB1Changing(string value);
    partial void OnDrivingLicenseB1Changed();
    partial void OnDrivingLicenseB1ExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnDrivingLicenseB1ExpireChanged();
    partial void OnDrivingLicenseB2Changing(string value);
    partial void OnDrivingLicenseB2Changed();
    partial void OnDrivingLicenseB2ExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnDrivingLicenseB2ExpireChanged();
    partial void OnPaymentTypeChanging(System.Nullable<int> value);
    partial void OnPaymentTypeChanged();
    partial void OnEffectiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEffectiveDateChanged();
    partial void OnResignDateChanging(System.Nullable<System.DateTime> value);
    partial void OnResignDateChanged();
    partial void OnJoinDateChanging(System.Nullable<System.DateTime> value);
    partial void OnJoinDateChanged();
    partial void OnEndEffectiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndEffectiveDateChanged();
    partial void OnBasicSalaryTypeChanging(System.Nullable<int> value);
    partial void OnBasicSalaryTypeChanged();
    partial void OnBasicSalaryChanging(System.Nullable<decimal> value);
    partial void OnBasicSalaryChanged();
    partial void OnBasicSalaryComponentIdChanging(System.Nullable<System.Guid> value);
    partial void OnBasicSalaryComponentIdChanged();
    partial void OnTaxStatusChanging(System.Nullable<int> value);
    partial void OnTaxStatusChanged();
    partial void OnCreatedByChanging(System.Nullable<System.Guid> value);
    partial void OnCreatedByChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnModifiedByChanging(System.Nullable<System.Guid> value);
    partial void OnModifiedByChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnfJPKChanging(System.Nullable<bool> value);
    partial void OnfJPKChanged();
    partial void OnJPKDateChanging(System.Nullable<System.DateTime> value);
    partial void OnJPKDateChanged();
    partial void OnfPensionFundChanging(System.Nullable<bool> value);
    partial void OnfPensionFundChanged();
    partial void OnPensionFundNoChanging(string value);
    partial void OnPensionFundNoChanged();
    partial void OnPensionFundDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPensionFundDateChanged();
    partial void OnPensionNoChanging(string value);
    partial void OnPensionNoChanged();
    partial void OnfPensionChanging(System.Nullable<bool> value);
    partial void OnfPensionChanged();
    partial void OnJKKChanging(System.Nullable<int> value);
    partial void OnJKKChanged();
    partial void OnJamSosTekNoChanging(string value);
    partial void OnJamSosTekNoChanged();
    partial void OnJamSosTekDateChanging(System.Nullable<System.DateTime> value);
    partial void OnJamSosTekDateChanged();
    partial void OnfJamSosTekChanging(System.Nullable<bool> value);
    partial void OnfJamSosTekChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnClaimTaxTypeChanging(System.Nullable<int> value);
    partial void OnClaimTaxTypeChanged();
    partial void OnLeaveCompensationTaxTypeChanging(System.Nullable<int> value);
    partial void OnLeaveCompensationTaxTypeChanged();
    partial void OnSourceTypeChanging(System.Nullable<int> value);
    partial void OnSourceTypeChanged();
    partial void OnFlexibleTimeChanging(System.Nullable<bool> value);
    partial void OnFlexibleTimeChanged();
    partial void OnJamSosTekTaxTypeChanging(System.Nullable<int> value);
    partial void OnJamSosTekTaxTypeChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnEmployeeTaxStatusChanging(System.Nullable<int> value);
    partial void OnEmployeeTaxStatusChanged();
    partial void OnEBasicSalaryChanging(string value);
    partial void OnEBasicSalaryChanged();
    partial void OnEStatusChanging(System.Nullable<int> value);
    partial void OnEStatusChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSignatureDrawingChanging(System.Data.Linq.Binary value);
    partial void OnSignatureDrawingChanged();
    partial void OnResetPasswordChanging(System.Nullable<bool> value);
    partial void OnResetPasswordChanged();
    partial void OnBegRSalaryNettoChanging(System.Nullable<decimal> value);
    partial void OnBegRSalaryNettoChanged();
    partial void OnBegRPPH21Changing(System.Nullable<decimal> value);
    partial void OnBegRPPH21Changed();
    partial void OnPhoneExtensionChanging(string value);
    partial void OnPhoneExtensionChanged();
    partial void OnRehireEmployeeIdChanging(System.Nullable<System.Guid> value);
    partial void OnRehireEmployeeIdChanged();
    partial void OnPensionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPensionDateChanged();
    partial void OnNPPJamsostekIdChanging(System.Nullable<System.Guid> value);
    partial void OnNPPJamsostekIdChanged();
    partial void OnfJHTChanging(System.Nullable<int> value);
    partial void OnfJHTChanged();
    partial void OnPayrollLastRunDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPayrollLastRunDateChanged();
    partial void OnAttendanceLastRunDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAttendanceLastRunDateChanged();
    partial void OnHumanResourcesLastRunDateChanging(System.Nullable<System.DateTime> value);
    partial void OnHumanResourcesLastRunDateChanged();
    partial void OnfBPJSChanging(System.Nullable<bool> value);
    partial void OnfBPJSChanged();
    partial void OnBPJSDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBPJSDateChanged();
    partial void OnBPJSNoChanging(string value);
    partial void OnBPJSNoChanged();
    partial void OnPaymentStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPaymentStartDateChanged();
    partial void OnBPJSFamilyChanging(System.Nullable<int> value);
    partial void OnBPJSFamilyChanged();
    partial void OnfForeignChanging(System.Nullable<bool> value);
    partial void OnfForeignChanged();
    partial void OnTaxCountryCodeChanging(System.Nullable<int> value);
    partial void OnTaxCountryCodeChanged();
    partial void OnKITASChanging(string value);
    partial void OnKITASChanged();
    partial void OnKITASExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnKITASExpireChanged();
    partial void OnPassportChanging(string value);
    partial void OnPassportChanged();
    partial void OnPassportExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnPassportExpireChanged();
    partial void OnfJPChanging(System.Nullable<bool> value);
    partial void OnfJPChanged();
    partial void OnJPDateChanging(System.Nullable<System.DateTime> value);
    partial void OnJPDateChanged();
    partial void OnFamilyCardNumberChanging(string value);
    partial void OnFamilyCardNumberChanged();
    partial void OnFamilyCardNumberExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnFamilyCardNumberExpireChanged();
    partial void OnJoinDateRehireChanging(System.Nullable<System.DateTime> value);
    partial void OnJoinDateRehireChanged();
    partial void OnFirstEmploymentDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFirstEmploymentDateChanged();
    partial void OnHireTypeChanging(System.Nullable<int> value);
    partial void OnHireTypeChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnCity1Changing(string value);
    partial void OnCity1Changed();
    partial void OnCity2Changing(string value);
    partial void OnCity2Changed();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnZipCode1Changing(string value);
    partial void OnZipCode1Changed();
    partial void OnZipCode2Changing(string value);
    partial void OnZipCode2Changed();
    partial void OnEmailLinkageChanging(string value);
    partial void OnEmailLinkageChanged();
    partial void OnEmailPayslipChanging(string value);
    partial void OnEmailPayslipChanged();
    #endregion
		
		public _Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(20)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="VarChar(20)")]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(100)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitDrawing", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary UnitDrawing
		{
			get
			{
				return this._UnitDrawing;
			}
			set
			{
				if ((this._UnitDrawing != value))
				{
					this.OnUnitDrawingChanging(value);
					this.SendPropertyChanging();
					this._UnitDrawing = value;
					this.SendPropertyChanged("UnitDrawing");
					this.OnUnitDrawingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(1500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(1500)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(1500)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandPhone", DbType="VarChar(50)")]
		public string HandPhone
		{
			get
			{
				return this._HandPhone;
			}
			set
			{
				if ((this._HandPhone != value))
				{
					this.OnHandPhoneChanging(value);
					this.SendPropertyChanging();
					this._HandPhone = value;
					this.SendPropertyChanged("HandPhone");
					this.OnHandPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(500)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="Int")]
		public System.Nullable<int> Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this.OnReligionChanging(value);
					this.SendPropertyChanging();
					this._Religion = value;
					this.SendPropertyChanged("Religion");
					this.OnReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
		public System.Nullable<int> Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hobby", DbType="VarChar(1500)")]
		public string Hobby
		{
			get
			{
				return this._Hobby;
			}
			set
			{
				if ((this._Hobby != value))
				{
					this.OnHobbyChanging(value);
					this.SendPropertyChanging();
					this._Hobby = value;
					this.SendPropertyChanged("Hobby");
					this.OnHobbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="Int")]
		public System.Nullable<int> MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this.OnMaritalStatusChanging(value);
					this.SendPropertyChanging();
					this._MaritalStatus = value;
					this.SendPropertyChanged("MaritalStatus");
					this.OnMaritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeStatus", DbType="Int")]
		public System.Nullable<int> EmployeeStatus
		{
			get
			{
				return this._EmployeeStatus;
			}
			set
			{
				if ((this._EmployeeStatus != value))
				{
					this.OnEmployeeStatusChanging(value);
					this.SendPropertyChanging();
					this._EmployeeStatus = value;
					this.SendPropertyChanged("EmployeeStatus");
					this.OnEmployeeStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverTimeStatus", DbType="Int")]
		public System.Nullable<int> OverTimeStatus
		{
			get
			{
				return this._OverTimeStatus;
			}
			set
			{
				if ((this._OverTimeStatus != value))
				{
					this.OnOverTimeStatusChanging(value);
					this.SendPropertyChanging();
					this._OverTimeStatus = value;
					this.SendPropertyChanged("OverTimeStatus");
					this.OnOverTimeStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverTimeGroupId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> OverTimeGroupId
		{
			get
			{
				return this._OverTimeGroupId;
			}
			set
			{
				if ((this._OverTimeGroupId != value))
				{
					this.OnOverTimeGroupIdChanging(value);
					this.SendPropertyChanging();
					this._OverTimeGroupId = value;
					this.SendPropertyChanged("OverTimeGroupId");
					this.OnOverTimeGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseRateGroupId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> BaseRateGroupId
		{
			get
			{
				return this._BaseRateGroupId;
			}
			set
			{
				if ((this._BaseRateGroupId != value))
				{
					this.OnBaseRateGroupIdChanging(value);
					this.SendPropertyChanging();
					this._BaseRateGroupId = value;
					this.SendPropertyChanged("BaseRateGroupId");
					this.OnBaseRateGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointOfHire", DbType="VarChar(50)")]
		public string PointOfHire
		{
			get
			{
				return this._PointOfHire;
			}
			set
			{
				if ((this._PointOfHire != value))
				{
					this.OnPointOfHireChanging(value);
					this.SendPropertyChanging();
					this._PointOfHire = value;
					this.SendPropertyChanged("PointOfHire");
					this.OnPointOfHireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPWP", DbType="VarChar(50)")]
		public string NPWP
		{
			get
			{
				return this._NPWP;
			}
			set
			{
				if ((this._NPWP != value))
				{
					this.OnNPWPChanging(value);
					this.SendPropertyChanging();
					this._NPWP = value;
					this.SendPropertyChanged("NPWP");
					this.OnNPWPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPWPDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NPWPDate
		{
			get
			{
				return this._NPWPDate;
			}
			set
			{
				if ((this._NPWPDate != value))
				{
					this.OnNPWPDateChanging(value);
					this.SendPropertyChanging();
					this._NPWPDate = value;
					this.SendPropertyChanged("NPWPDate");
					this.OnNPWPDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fNPWP", DbType="Bit")]
		public System.Nullable<bool> fNPWP
		{
			get
			{
				return this._fNPWP;
			}
			set
			{
				if ((this._fNPWP != value))
				{
					this.OnfNPWPChanging(value);
					this.SendPropertyChanging();
					this._fNPWP = value;
					this.SendPropertyChanged("fNPWP");
					this.OnfNPWPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoNumber", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> AutoNumber
		{
			get
			{
				return this._AutoNumber;
			}
			set
			{
				if ((this._AutoNumber != value))
				{
					this.OnAutoNumberChanging(value);
					this.SendPropertyChanging();
					this._AutoNumber = value;
					this.SendPropertyChanged("AutoNumber");
					this.OnAutoNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact1", DbType="VarChar(1500)")]
		public string Contact1
		{
			get
			{
				return this._Contact1;
			}
			set
			{
				if ((this._Contact1 != value))
				{
					this.OnContact1Changing(value);
					this.SendPropertyChanging();
					this._Contact1 = value;
					this.SendPropertyChanged("Contact1");
					this.OnContact1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact2", DbType="VarChar(1500)")]
		public string Contact2
		{
			get
			{
				return this._Contact2;
			}
			set
			{
				if ((this._Contact2 != value))
				{
					this.OnContact2Changing(value);
					this.SendPropertyChanging();
					this._Contact2 = value;
					this.SendPropertyChanged("Contact2");
					this.OnContact2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(1500)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceOfBirth", DbType="VarChar(50)")]
		public string PlaceOfBirth
		{
			get
			{
				return this._PlaceOfBirth;
			}
			set
			{
				if ((this._PlaceOfBirth != value))
				{
					this.OnPlaceOfBirthChanging(value);
					this.SendPropertyChanging();
					this._PlaceOfBirth = value;
					this.SendPropertyChanged("PlaceOfBirth");
					this.OnPlaceOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> BranchId
		{
			get
			{
				return this._BranchId;
			}
			set
			{
				if ((this._BranchId != value))
				{
					this.OnBranchIdChanging(value);
					this.SendPropertyChanging();
					this._BranchId = value;
					this.SendPropertyChanged("BranchId");
					this.OnBranchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> JobId
		{
			get
			{
				return this._JobId;
			}
			set
			{
				if ((this._JobId != value))
				{
					this.OnJobIdChanging(value);
					this.SendPropertyChanging();
					this._JobId = value;
					this.SendPropertyChanged("JobId");
					this.OnJobIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> OrganizationId
		{
			get
			{
				return this._OrganizationId;
			}
			set
			{
				if ((this._OrganizationId != value))
				{
					this.OnOrganizationIdChanging(value);
					this.SendPropertyChanging();
					this._OrganizationId = value;
					this.SendPropertyChanged("OrganizationId");
					this.OnOrganizationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ClassId
		{
			get
			{
				return this._ClassId;
			}
			set
			{
				if ((this._ClassId != value))
				{
					this.OnClassIdChanging(value);
					this.SendPropertyChanging();
					this._ClassId = value;
					this.SendPropertyChanged("ClassId");
					this.OnClassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodType", DbType="Int")]
		public System.Nullable<int> BloodType
		{
			get
			{
				return this._BloodType;
			}
			set
			{
				if ((this._BloodType != value))
				{
					this.OnBloodTypeChanging(value);
					this.SendPropertyChanging();
					this._BloodType = value;
					this.SendPropertyChanged("BloodType");
					this.OnBloodTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="VarChar(50)")]
		public string Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="VarChar(50)")]
		public string Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ethnic", DbType="VarChar(50)")]
		public string Ethnic
		{
			get
			{
				return this._Ethnic;
			}
			set
			{
				if ((this._Ethnic != value))
				{
					this.OnEthnicChanging(value);
					this.SendPropertyChanging();
					this._Ethnic = value;
					this.SendPropertyChanged("Ethnic");
					this.OnEthnicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNumber", DbType="VarChar(50)")]
		public string IdNumber
		{
			get
			{
				return this._IdNumber;
			}
			set
			{
				if ((this._IdNumber != value))
				{
					this.OnIdNumberChanging(value);
					this.SendPropertyChanging();
					this._IdNumber = value;
					this.SendPropertyChanged("IdNumber");
					this.OnIdNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNumberExpire", DbType="DateTime")]
		public System.Nullable<System.DateTime> IdNumberExpire
		{
			get
			{
				return this._IdNumberExpire;
			}
			set
			{
				if ((this._IdNumberExpire != value))
				{
					this.OnIdNumberExpireChanging(value);
					this.SendPropertyChanging();
					this._IdNumberExpire = value;
					this.SendPropertyChanged("IdNumberExpire");
					this.OnIdNumberExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseA", DbType="VarChar(50)")]
		public string DrivingLicenseA
		{
			get
			{
				return this._DrivingLicenseA;
			}
			set
			{
				if ((this._DrivingLicenseA != value))
				{
					this.OnDrivingLicenseAChanging(value);
					this.SendPropertyChanging();
					this._DrivingLicenseA = value;
					this.SendPropertyChanged("DrivingLicenseA");
					this.OnDrivingLicenseAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseAExpire", DbType="DateTime")]
		public System.Nullable<System.DateTime> DrivingLicenseAExpire
		{
			get
			{
				return this._DrivingLicenseAExpire;
			}
			set
			{
				if ((this._DrivingLicenseAExpire != value))
				{
					this.OnDrivingLicenseAExpireChanging(value);
					this.SendPropertyChanging();
					this._DrivingLicenseAExpire = value;
					this.SendPropertyChanged("DrivingLicenseAExpire");
					this.OnDrivingLicenseAExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseB", DbType="VarChar(50)")]
		public string DrivingLicenseB
		{
			get
			{
				return this._DrivingLicenseB;
			}
			set
			{
				if ((this._DrivingLicenseB != value))
				{
					this.OnDrivingLicenseBChanging(value);
					this.SendPropertyChanging();
					this._DrivingLicenseB = value;
					this.SendPropertyChanged("DrivingLicenseB");
					this.OnDrivingLicenseBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseBExpire", DbType="DateTime")]
		public System.Nullable<System.DateTime> DrivingLicenseBExpire
		{
			get
			{
				return this._DrivingLicenseBExpire;
			}
			set
			{
				if ((this._DrivingLicenseBExpire != value))
				{
					this.OnDrivingLicenseBExpireChanging(value);
					this.SendPropertyChanging();
					this._DrivingLicenseBExpire = value;
					this.SendPropertyChanged("DrivingLicenseBExpire");
					this.OnDrivingLicenseBExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseC", DbType="VarChar(50)")]
		public string DrivingLicenseC
		{
			get
			{
				return this._DrivingLicenseC;
			}
			set
			{
				if ((this._DrivingLicenseC != value))
				{
					this.OnDrivingLicenseCChanging(value);
					this.SendPropertyChanging();
					this._DrivingLicenseC = value;
					this.SendPropertyChanged("DrivingLicenseC");
					this.OnDrivingLicenseCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseCExpire", DbType="DateTime")]
		public System.Nullable<System.DateTime> DrivingLicenseCExpire
		{
			get
			{
				return this._DrivingLicenseCExpire;
			}
			set
			{
				if ((this._DrivingLicenseCExpire != value))
				{
					this.OnDrivingLicenseCExpireChanging(value);
					this.SendPropertyChanging();
					this._DrivingLicenseCExpire = value;
					this.SendPropertyChanged("DrivingLicenseCExpire");
					this.OnDrivingLicenseCExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseB1", DbType="VarChar(50)")]
		public string DrivingLicenseB1
		{
			get
			{
				return this._DrivingLicenseB1;
			}
			set
			{
				if ((this._DrivingLicenseB1 != value))
				{
					this.OnDrivingLicenseB1Changing(value);
					this.SendPropertyChanging();
					this._DrivingLicenseB1 = value;
					this.SendPropertyChanged("DrivingLicenseB1");
					this.OnDrivingLicenseB1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseB1Expire", DbType="DateTime")]
		public System.Nullable<System.DateTime> DrivingLicenseB1Expire
		{
			get
			{
				return this._DrivingLicenseB1Expire;
			}
			set
			{
				if ((this._DrivingLicenseB1Expire != value))
				{
					this.OnDrivingLicenseB1ExpireChanging(value);
					this.SendPropertyChanging();
					this._DrivingLicenseB1Expire = value;
					this.SendPropertyChanged("DrivingLicenseB1Expire");
					this.OnDrivingLicenseB1ExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseB2", DbType="VarChar(50)")]
		public string DrivingLicenseB2
		{
			get
			{
				return this._DrivingLicenseB2;
			}
			set
			{
				if ((this._DrivingLicenseB2 != value))
				{
					this.OnDrivingLicenseB2Changing(value);
					this.SendPropertyChanging();
					this._DrivingLicenseB2 = value;
					this.SendPropertyChanged("DrivingLicenseB2");
					this.OnDrivingLicenseB2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivingLicenseB2Expire", DbType="DateTime")]
		public System.Nullable<System.DateTime> DrivingLicenseB2Expire
		{
			get
			{
				return this._DrivingLicenseB2Expire;
			}
			set
			{
				if ((this._DrivingLicenseB2Expire != value))
				{
					this.OnDrivingLicenseB2ExpireChanging(value);
					this.SendPropertyChanging();
					this._DrivingLicenseB2Expire = value;
					this.SendPropertyChanged("DrivingLicenseB2Expire");
					this.OnDrivingLicenseB2ExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="Int")]
		public System.Nullable<int> PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this.OnPaymentTypeChanging(value);
					this.SendPropertyChanging();
					this._PaymentType = value;
					this.SendPropertyChanged("PaymentType");
					this.OnPaymentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectiveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EffectiveDate
		{
			get
			{
				return this._EffectiveDate;
			}
			set
			{
				if ((this._EffectiveDate != value))
				{
					this.OnEffectiveDateChanging(value);
					this.SendPropertyChanging();
					this._EffectiveDate = value;
					this.SendPropertyChanged("EffectiveDate");
					this.OnEffectiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResignDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResignDate
		{
			get
			{
				return this._ResignDate;
			}
			set
			{
				if ((this._ResignDate != value))
				{
					this.OnResignDateChanging(value);
					this.SendPropertyChanging();
					this._ResignDate = value;
					this.SendPropertyChanged("ResignDate");
					this.OnResignDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> JoinDate
		{
			get
			{
				return this._JoinDate;
			}
			set
			{
				if ((this._JoinDate != value))
				{
					this.OnJoinDateChanging(value);
					this.SendPropertyChanging();
					this._JoinDate = value;
					this.SendPropertyChanged("JoinDate");
					this.OnJoinDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndEffectiveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndEffectiveDate
		{
			get
			{
				return this._EndEffectiveDate;
			}
			set
			{
				if ((this._EndEffectiveDate != value))
				{
					this.OnEndEffectiveDateChanging(value);
					this.SendPropertyChanging();
					this._EndEffectiveDate = value;
					this.SendPropertyChanged("EndEffectiveDate");
					this.OnEndEffectiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSalaryType", DbType="Int")]
		public System.Nullable<int> BasicSalaryType
		{
			get
			{
				return this._BasicSalaryType;
			}
			set
			{
				if ((this._BasicSalaryType != value))
				{
					this.OnBasicSalaryTypeChanging(value);
					this.SendPropertyChanging();
					this._BasicSalaryType = value;
					this.SendPropertyChanged("BasicSalaryType");
					this.OnBasicSalaryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSalary", DbType="Money")]
		public System.Nullable<decimal> BasicSalary
		{
			get
			{
				return this._BasicSalary;
			}
			set
			{
				if ((this._BasicSalary != value))
				{
					this.OnBasicSalaryChanging(value);
					this.SendPropertyChanging();
					this._BasicSalary = value;
					this.SendPropertyChanged("BasicSalary");
					this.OnBasicSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSalaryComponentId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> BasicSalaryComponentId
		{
			get
			{
				return this._BasicSalaryComponentId;
			}
			set
			{
				if ((this._BasicSalaryComponentId != value))
				{
					this.OnBasicSalaryComponentIdChanging(value);
					this.SendPropertyChanging();
					this._BasicSalaryComponentId = value;
					this.SendPropertyChanged("BasicSalaryComponentId");
					this.OnBasicSalaryComponentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxStatus", DbType="Int")]
		public System.Nullable<int> TaxStatus
		{
			get
			{
				return this._TaxStatus;
			}
			set
			{
				if ((this._TaxStatus != value))
				{
					this.OnTaxStatusChanging(value);
					this.SendPropertyChanging();
					this._TaxStatus = value;
					this.SendPropertyChanged("TaxStatus");
					this.OnTaxStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fJPK", DbType="Bit")]
		public System.Nullable<bool> fJPK
		{
			get
			{
				return this._fJPK;
			}
			set
			{
				if ((this._fJPK != value))
				{
					this.OnfJPKChanging(value);
					this.SendPropertyChanging();
					this._fJPK = value;
					this.SendPropertyChanged("fJPK");
					this.OnfJPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JPKDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> JPKDate
		{
			get
			{
				return this._JPKDate;
			}
			set
			{
				if ((this._JPKDate != value))
				{
					this.OnJPKDateChanging(value);
					this.SendPropertyChanging();
					this._JPKDate = value;
					this.SendPropertyChanged("JPKDate");
					this.OnJPKDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPensionFund", DbType="Bit")]
		public System.Nullable<bool> fPensionFund
		{
			get
			{
				return this._fPensionFund;
			}
			set
			{
				if ((this._fPensionFund != value))
				{
					this.OnfPensionFundChanging(value);
					this.SendPropertyChanging();
					this._fPensionFund = value;
					this.SendPropertyChanged("fPensionFund");
					this.OnfPensionFundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PensionFundNo", DbType="VarChar(50)")]
		public string PensionFundNo
		{
			get
			{
				return this._PensionFundNo;
			}
			set
			{
				if ((this._PensionFundNo != value))
				{
					this.OnPensionFundNoChanging(value);
					this.SendPropertyChanging();
					this._PensionFundNo = value;
					this.SendPropertyChanged("PensionFundNo");
					this.OnPensionFundNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PensionFundDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PensionFundDate
		{
			get
			{
				return this._PensionFundDate;
			}
			set
			{
				if ((this._PensionFundDate != value))
				{
					this.OnPensionFundDateChanging(value);
					this.SendPropertyChanging();
					this._PensionFundDate = value;
					this.SendPropertyChanged("PensionFundDate");
					this.OnPensionFundDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PensionNo", DbType="VarChar(50)")]
		public string PensionNo
		{
			get
			{
				return this._PensionNo;
			}
			set
			{
				if ((this._PensionNo != value))
				{
					this.OnPensionNoChanging(value);
					this.SendPropertyChanging();
					this._PensionNo = value;
					this.SendPropertyChanged("PensionNo");
					this.OnPensionNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPension", DbType="Bit")]
		public System.Nullable<bool> fPension
		{
			get
			{
				return this._fPension;
			}
			set
			{
				if ((this._fPension != value))
				{
					this.OnfPensionChanging(value);
					this.SendPropertyChanging();
					this._fPension = value;
					this.SendPropertyChanged("fPension");
					this.OnfPensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JKK", DbType="Int")]
		public System.Nullable<int> JKK
		{
			get
			{
				return this._JKK;
			}
			set
			{
				if ((this._JKK != value))
				{
					this.OnJKKChanging(value);
					this.SendPropertyChanging();
					this._JKK = value;
					this.SendPropertyChanged("JKK");
					this.OnJKKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JamSosTekNo", DbType="VarChar(50)")]
		public string JamSosTekNo
		{
			get
			{
				return this._JamSosTekNo;
			}
			set
			{
				if ((this._JamSosTekNo != value))
				{
					this.OnJamSosTekNoChanging(value);
					this.SendPropertyChanging();
					this._JamSosTekNo = value;
					this.SendPropertyChanged("JamSosTekNo");
					this.OnJamSosTekNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JamSosTekDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> JamSosTekDate
		{
			get
			{
				return this._JamSosTekDate;
			}
			set
			{
				if ((this._JamSosTekDate != value))
				{
					this.OnJamSosTekDateChanging(value);
					this.SendPropertyChanging();
					this._JamSosTekDate = value;
					this.SendPropertyChanged("JamSosTekDate");
					this.OnJamSosTekDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fJamSosTek", DbType="Bit")]
		public System.Nullable<bool> fJamSosTek
		{
			get
			{
				return this._fJamSosTek;
			}
			set
			{
				if ((this._fJamSosTek != value))
				{
					this.OnfJamSosTekChanging(value);
					this.SendPropertyChanging();
					this._fJamSosTek = value;
					this.SendPropertyChanged("fJamSosTek");
					this.OnfJamSosTekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimTaxType", DbType="Int")]
		public System.Nullable<int> ClaimTaxType
		{
			get
			{
				return this._ClaimTaxType;
			}
			set
			{
				if ((this._ClaimTaxType != value))
				{
					this.OnClaimTaxTypeChanging(value);
					this.SendPropertyChanging();
					this._ClaimTaxType = value;
					this.SendPropertyChanged("ClaimTaxType");
					this.OnClaimTaxTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveCompensationTaxType", DbType="Int")]
		public System.Nullable<int> LeaveCompensationTaxType
		{
			get
			{
				return this._LeaveCompensationTaxType;
			}
			set
			{
				if ((this._LeaveCompensationTaxType != value))
				{
					this.OnLeaveCompensationTaxTypeChanging(value);
					this.SendPropertyChanging();
					this._LeaveCompensationTaxType = value;
					this.SendPropertyChanged("LeaveCompensationTaxType");
					this.OnLeaveCompensationTaxTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceType", DbType="Int")]
		public System.Nullable<int> SourceType
		{
			get
			{
				return this._SourceType;
			}
			set
			{
				if ((this._SourceType != value))
				{
					this.OnSourceTypeChanging(value);
					this.SendPropertyChanging();
					this._SourceType = value;
					this.SendPropertyChanged("SourceType");
					this.OnSourceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlexibleTime", DbType="Bit")]
		public System.Nullable<bool> FlexibleTime
		{
			get
			{
				return this._FlexibleTime;
			}
			set
			{
				if ((this._FlexibleTime != value))
				{
					this.OnFlexibleTimeChanging(value);
					this.SendPropertyChanging();
					this._FlexibleTime = value;
					this.SendPropertyChanged("FlexibleTime");
					this.OnFlexibleTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JamSosTekTaxType", DbType="Int")]
		public System.Nullable<int> JamSosTekTaxType
		{
			get
			{
				return this._JamSosTekTaxType;
			}
			set
			{
				if ((this._JamSosTekTaxType != value))
				{
					this.OnJamSosTekTaxTypeChanging(value);
					this.SendPropertyChanging();
					this._JamSosTekTaxType = value;
					this.SendPropertyChanged("JamSosTekTaxType");
					this.OnJamSosTekTaxTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(50)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTaxStatus", DbType="Int")]
		public System.Nullable<int> EmployeeTaxStatus
		{
			get
			{
				return this._EmployeeTaxStatus;
			}
			set
			{
				if ((this._EmployeeTaxStatus != value))
				{
					this.OnEmployeeTaxStatusChanging(value);
					this.SendPropertyChanging();
					this._EmployeeTaxStatus = value;
					this.SendPropertyChanged("EmployeeTaxStatus");
					this.OnEmployeeTaxStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBasicSalary", DbType="VarChar(100)")]
		public string EBasicSalary
		{
			get
			{
				return this._EBasicSalary;
			}
			set
			{
				if ((this._EBasicSalary != value))
				{
					this.OnEBasicSalaryChanging(value);
					this.SendPropertyChanging();
					this._EBasicSalary = value;
					this.SendPropertyChanged("EBasicSalary");
					this.OnEBasicSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EStatus", DbType="Int")]
		public System.Nullable<int> EStatus
		{
			get
			{
				return this._EStatus;
			}
			set
			{
				if ((this._EStatus != value))
				{
					this.OnEStatusChanging(value);
					this.SendPropertyChanging();
					this._EStatus = value;
					this.SendPropertyChanged("EStatus");
					this.OnEStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(500)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignatureDrawing", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SignatureDrawing
		{
			get
			{
				return this._SignatureDrawing;
			}
			set
			{
				if ((this._SignatureDrawing != value))
				{
					this.OnSignatureDrawingChanging(value);
					this.SendPropertyChanging();
					this._SignatureDrawing = value;
					this.SendPropertyChanged("SignatureDrawing");
					this.OnSignatureDrawingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResetPassword", DbType="Bit")]
		public System.Nullable<bool> ResetPassword
		{
			get
			{
				return this._ResetPassword;
			}
			set
			{
				if ((this._ResetPassword != value))
				{
					this.OnResetPasswordChanging(value);
					this.SendPropertyChanging();
					this._ResetPassword = value;
					this.SendPropertyChanged("ResetPassword");
					this.OnResetPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BegRSalaryNetto", DbType="Money")]
		public System.Nullable<decimal> BegRSalaryNetto
		{
			get
			{
				return this._BegRSalaryNetto;
			}
			set
			{
				if ((this._BegRSalaryNetto != value))
				{
					this.OnBegRSalaryNettoChanging(value);
					this.SendPropertyChanging();
					this._BegRSalaryNetto = value;
					this.SendPropertyChanged("BegRSalaryNetto");
					this.OnBegRSalaryNettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BegRPPH21", DbType="Money")]
		public System.Nullable<decimal> BegRPPH21
		{
			get
			{
				return this._BegRPPH21;
			}
			set
			{
				if ((this._BegRPPH21 != value))
				{
					this.OnBegRPPH21Changing(value);
					this.SendPropertyChanging();
					this._BegRPPH21 = value;
					this.SendPropertyChanged("BegRPPH21");
					this.OnBegRPPH21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneExtension", DbType="VarChar(10)")]
		public string PhoneExtension
		{
			get
			{
				return this._PhoneExtension;
			}
			set
			{
				if ((this._PhoneExtension != value))
				{
					this.OnPhoneExtensionChanging(value);
					this.SendPropertyChanging();
					this._PhoneExtension = value;
					this.SendPropertyChanged("PhoneExtension");
					this.OnPhoneExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RehireEmployeeId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> RehireEmployeeId
		{
			get
			{
				return this._RehireEmployeeId;
			}
			set
			{
				if ((this._RehireEmployeeId != value))
				{
					this.OnRehireEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._RehireEmployeeId = value;
					this.SendPropertyChanged("RehireEmployeeId");
					this.OnRehireEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PensionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PensionDate
		{
			get
			{
				return this._PensionDate;
			}
			set
			{
				if ((this._PensionDate != value))
				{
					this.OnPensionDateChanging(value);
					this.SendPropertyChanging();
					this._PensionDate = value;
					this.SendPropertyChanged("PensionDate");
					this.OnPensionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPPJamsostekId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NPPJamsostekId
		{
			get
			{
				return this._NPPJamsostekId;
			}
			set
			{
				if ((this._NPPJamsostekId != value))
				{
					this.OnNPPJamsostekIdChanging(value);
					this.SendPropertyChanging();
					this._NPPJamsostekId = value;
					this.SendPropertyChanged("NPPJamsostekId");
					this.OnNPPJamsostekIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fJHT", DbType="Int")]
		public System.Nullable<int> fJHT
		{
			get
			{
				return this._fJHT;
			}
			set
			{
				if ((this._fJHT != value))
				{
					this.OnfJHTChanging(value);
					this.SendPropertyChanging();
					this._fJHT = value;
					this.SendPropertyChanged("fJHT");
					this.OnfJHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayrollLastRunDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PayrollLastRunDate
		{
			get
			{
				return this._PayrollLastRunDate;
			}
			set
			{
				if ((this._PayrollLastRunDate != value))
				{
					this.OnPayrollLastRunDateChanging(value);
					this.SendPropertyChanging();
					this._PayrollLastRunDate = value;
					this.SendPropertyChanged("PayrollLastRunDate");
					this.OnPayrollLastRunDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendanceLastRunDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AttendanceLastRunDate
		{
			get
			{
				return this._AttendanceLastRunDate;
			}
			set
			{
				if ((this._AttendanceLastRunDate != value))
				{
					this.OnAttendanceLastRunDateChanging(value);
					this.SendPropertyChanging();
					this._AttendanceLastRunDate = value;
					this.SendPropertyChanged("AttendanceLastRunDate");
					this.OnAttendanceLastRunDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HumanResourcesLastRunDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> HumanResourcesLastRunDate
		{
			get
			{
				return this._HumanResourcesLastRunDate;
			}
			set
			{
				if ((this._HumanResourcesLastRunDate != value))
				{
					this.OnHumanResourcesLastRunDateChanging(value);
					this.SendPropertyChanging();
					this._HumanResourcesLastRunDate = value;
					this.SendPropertyChanged("HumanResourcesLastRunDate");
					this.OnHumanResourcesLastRunDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBPJS", DbType="Bit")]
		public System.Nullable<bool> fBPJS
		{
			get
			{
				return this._fBPJS;
			}
			set
			{
				if ((this._fBPJS != value))
				{
					this.OnfBPJSChanging(value);
					this.SendPropertyChanging();
					this._fBPJS = value;
					this.SendPropertyChanged("fBPJS");
					this.OnfBPJSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPJSDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BPJSDate
		{
			get
			{
				return this._BPJSDate;
			}
			set
			{
				if ((this._BPJSDate != value))
				{
					this.OnBPJSDateChanging(value);
					this.SendPropertyChanging();
					this._BPJSDate = value;
					this.SendPropertyChanged("BPJSDate");
					this.OnBPJSDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPJSNo", DbType="VarChar(50)")]
		public string BPJSNo
		{
			get
			{
				return this._BPJSNo;
			}
			set
			{
				if ((this._BPJSNo != value))
				{
					this.OnBPJSNoChanging(value);
					this.SendPropertyChanging();
					this._BPJSNo = value;
					this.SendPropertyChanged("BPJSNo");
					this.OnBPJSNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaymentStartDate
		{
			get
			{
				return this._PaymentStartDate;
			}
			set
			{
				if ((this._PaymentStartDate != value))
				{
					this.OnPaymentStartDateChanging(value);
					this.SendPropertyChanging();
					this._PaymentStartDate = value;
					this.SendPropertyChanged("PaymentStartDate");
					this.OnPaymentStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPJSFamily", DbType="Int")]
		public System.Nullable<int> BPJSFamily
		{
			get
			{
				return this._BPJSFamily;
			}
			set
			{
				if ((this._BPJSFamily != value))
				{
					this.OnBPJSFamilyChanging(value);
					this.SendPropertyChanging();
					this._BPJSFamily = value;
					this.SendPropertyChanged("BPJSFamily");
					this.OnBPJSFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fForeign", DbType="Bit")]
		public System.Nullable<bool> fForeign
		{
			get
			{
				return this._fForeign;
			}
			set
			{
				if ((this._fForeign != value))
				{
					this.OnfForeignChanging(value);
					this.SendPropertyChanging();
					this._fForeign = value;
					this.SendPropertyChanged("fForeign");
					this.OnfForeignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCountryCode", DbType="Int")]
		public System.Nullable<int> TaxCountryCode
		{
			get
			{
				return this._TaxCountryCode;
			}
			set
			{
				if ((this._TaxCountryCode != value))
				{
					this.OnTaxCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._TaxCountryCode = value;
					this.SendPropertyChanged("TaxCountryCode");
					this.OnTaxCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KITAS", DbType="VarChar(50)")]
		public string KITAS
		{
			get
			{
				return this._KITAS;
			}
			set
			{
				if ((this._KITAS != value))
				{
					this.OnKITASChanging(value);
					this.SendPropertyChanging();
					this._KITAS = value;
					this.SendPropertyChanged("KITAS");
					this.OnKITASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KITASExpire", DbType="DateTime")]
		public System.Nullable<System.DateTime> KITASExpire
		{
			get
			{
				return this._KITASExpire;
			}
			set
			{
				if ((this._KITASExpire != value))
				{
					this.OnKITASExpireChanging(value);
					this.SendPropertyChanging();
					this._KITASExpire = value;
					this.SendPropertyChanged("KITASExpire");
					this.OnKITASExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passport", DbType="VarChar(50)")]
		public string Passport
		{
			get
			{
				return this._Passport;
			}
			set
			{
				if ((this._Passport != value))
				{
					this.OnPassportChanging(value);
					this.SendPropertyChanging();
					this._Passport = value;
					this.SendPropertyChanged("Passport");
					this.OnPassportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportExpire", DbType="DateTime")]
		public System.Nullable<System.DateTime> PassportExpire
		{
			get
			{
				return this._PassportExpire;
			}
			set
			{
				if ((this._PassportExpire != value))
				{
					this.OnPassportExpireChanging(value);
					this.SendPropertyChanging();
					this._PassportExpire = value;
					this.SendPropertyChanged("PassportExpire");
					this.OnPassportExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fJP", DbType="Bit")]
		public System.Nullable<bool> fJP
		{
			get
			{
				return this._fJP;
			}
			set
			{
				if ((this._fJP != value))
				{
					this.OnfJPChanging(value);
					this.SendPropertyChanging();
					this._fJP = value;
					this.SendPropertyChanged("fJP");
					this.OnfJPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JPDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> JPDate
		{
			get
			{
				return this._JPDate;
			}
			set
			{
				if ((this._JPDate != value))
				{
					this.OnJPDateChanging(value);
					this.SendPropertyChanging();
					this._JPDate = value;
					this.SendPropertyChanged("JPDate");
					this.OnJPDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyCardNumber", DbType="VarChar(50)")]
		public string FamilyCardNumber
		{
			get
			{
				return this._FamilyCardNumber;
			}
			set
			{
				if ((this._FamilyCardNumber != value))
				{
					this.OnFamilyCardNumberChanging(value);
					this.SendPropertyChanging();
					this._FamilyCardNumber = value;
					this.SendPropertyChanged("FamilyCardNumber");
					this.OnFamilyCardNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyCardNumberExpire", DbType="DateTime")]
		public System.Nullable<System.DateTime> FamilyCardNumberExpire
		{
			get
			{
				return this._FamilyCardNumberExpire;
			}
			set
			{
				if ((this._FamilyCardNumberExpire != value))
				{
					this.OnFamilyCardNumberExpireChanging(value);
					this.SendPropertyChanging();
					this._FamilyCardNumberExpire = value;
					this.SendPropertyChanged("FamilyCardNumberExpire");
					this.OnFamilyCardNumberExpireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinDateRehire", DbType="DateTime")]
		public System.Nullable<System.DateTime> JoinDateRehire
		{
			get
			{
				return this._JoinDateRehire;
			}
			set
			{
				if ((this._JoinDateRehire != value))
				{
					this.OnJoinDateRehireChanging(value);
					this.SendPropertyChanging();
					this._JoinDateRehire = value;
					this.SendPropertyChanged("JoinDateRehire");
					this.OnJoinDateRehireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstEmploymentDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FirstEmploymentDate
		{
			get
			{
				return this._FirstEmploymentDate;
			}
			set
			{
				if ((this._FirstEmploymentDate != value))
				{
					this.OnFirstEmploymentDateChanging(value);
					this.SendPropertyChanging();
					this._FirstEmploymentDate = value;
					this.SendPropertyChanged("FirstEmploymentDate");
					this.OnFirstEmploymentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HireType", DbType="Int")]
		public System.Nullable<int> HireType
		{
			get
			{
				return this._HireType;
			}
			set
			{
				if ((this._HireType != value))
				{
					this.OnHireTypeChanging(value);
					this.SendPropertyChanging();
					this._HireType = value;
					this.SendPropertyChanged("HireType");
					this.OnHireTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City1", DbType="VarChar(MAX)")]
		public string City1
		{
			get
			{
				return this._City1;
			}
			set
			{
				if ((this._City1 != value))
				{
					this.OnCity1Changing(value);
					this.SendPropertyChanging();
					this._City1 = value;
					this.SendPropertyChanged("City1");
					this.OnCity1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City2", DbType="VarChar(MAX)")]
		public string City2
		{
			get
			{
				return this._City2;
			}
			set
			{
				if ((this._City2 != value))
				{
					this.OnCity2Changing(value);
					this.SendPropertyChanging();
					this._City2 = value;
					this.SendPropertyChanged("City2");
					this.OnCity2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="VarChar(MAX)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode1", DbType="VarChar(MAX)")]
		public string ZipCode1
		{
			get
			{
				return this._ZipCode1;
			}
			set
			{
				if ((this._ZipCode1 != value))
				{
					this.OnZipCode1Changing(value);
					this.SendPropertyChanging();
					this._ZipCode1 = value;
					this.SendPropertyChanged("ZipCode1");
					this.OnZipCode1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode2", DbType="VarChar(MAX)")]
		public string ZipCode2
		{
			get
			{
				return this._ZipCode2;
			}
			set
			{
				if ((this._ZipCode2 != value))
				{
					this.OnZipCode2Changing(value);
					this.SendPropertyChanging();
					this._ZipCode2 = value;
					this.SendPropertyChanged("ZipCode2");
					this.OnZipCode2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailLinkage", DbType="VarChar(100)")]
		public string EmailLinkage
		{
			get
			{
				return this._EmailLinkage;
			}
			set
			{
				if ((this._EmailLinkage != value))
				{
					this.OnEmailLinkageChanging(value);
					this.SendPropertyChanging();
					this._EmailLinkage = value;
					this.SendPropertyChanged("EmailLinkage");
					this.OnEmailLinkageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailPayslip", DbType="VarChar(100)")]
		public string EmailPayslip
		{
			get
			{
				return this._EmailPayslip;
			}
			set
			{
				if ((this._EmailPayslip != value))
				{
					this.OnEmailPayslipChanging(value);
					this.SendPropertyChanging();
					this._EmailPayslip = value;
					this.SendPropertyChanged("EmailPayslip");
					this.OnEmailPayslipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_EmployeeEmergeLeave]")]
	public partial class _EmployeeEmergeLeave : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Nullable<System.Guid> _EmployeeId;
		
		private System.Nullable<int> _Total;
		
		private System.Nullable<int> _Planning;
		
		private System.Nullable<int> _Claimed;
		
		private System.Nullable<int> _UnitType;
		
		private int _Type;
		
		private System.Nullable<System.Guid> _LeaveId;
		
		private System.Nullable<System.DateTime> _EffectiveDate;
		
		private System.Nullable<System.DateTime> _ExpiredDate;
		
		private System.Nullable<System.DateTime> _OriginalExpiredDate;
		
		private System.Nullable<bool> _Extended;
		
		private System.Guid _ParentId;
		
		private System.Nullable<bool> _Expired;
		
		private System.Nullable<System.Guid> _ReferenceId;
		
		private System.Nullable<bool> _Calculate;
		
		private System.Nullable<System.Guid> _LeaveCodeId;
		
		private System.Nullable<int> _LeaveType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnEmployeeIdChanging(System.Nullable<System.Guid> value);
    partial void OnEmployeeIdChanged();
    partial void OnTotalChanging(System.Nullable<int> value);
    partial void OnTotalChanged();
    partial void OnPlanningChanging(System.Nullable<int> value);
    partial void OnPlanningChanged();
    partial void OnClaimedChanging(System.Nullable<int> value);
    partial void OnClaimedChanged();
    partial void OnUnitTypeChanging(System.Nullable<int> value);
    partial void OnUnitTypeChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnLeaveIdChanging(System.Nullable<System.Guid> value);
    partial void OnLeaveIdChanged();
    partial void OnEffectiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEffectiveDateChanged();
    partial void OnExpiredDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiredDateChanged();
    partial void OnOriginalExpiredDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOriginalExpiredDateChanged();
    partial void OnExtendedChanging(System.Nullable<bool> value);
    partial void OnExtendedChanged();
    partial void OnParentIdChanging(System.Guid value);
    partial void OnParentIdChanged();
    partial void OnExpiredChanging(System.Nullable<bool> value);
    partial void OnExpiredChanged();
    partial void OnReferenceIdChanging(System.Nullable<System.Guid> value);
    partial void OnReferenceIdChanged();
    partial void OnCalculateChanging(System.Nullable<bool> value);
    partial void OnCalculateChanged();
    partial void OnLeaveCodeIdChanging(System.Nullable<System.Guid> value);
    partial void OnLeaveCodeIdChanged();
    partial void OnLeaveTypeChanging(System.Nullable<int> value);
    partial void OnLeaveTypeChanged();
    #endregion
		
		public _EmployeeEmergeLeave()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Planning", DbType="Int")]
		public System.Nullable<int> Planning
		{
			get
			{
				return this._Planning;
			}
			set
			{
				if ((this._Planning != value))
				{
					this.OnPlanningChanging(value);
					this.SendPropertyChanging();
					this._Planning = value;
					this.SendPropertyChanged("Planning");
					this.OnPlanningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Claimed", DbType="Int")]
		public System.Nullable<int> Claimed
		{
			get
			{
				return this._Claimed;
			}
			set
			{
				if ((this._Claimed != value))
				{
					this.OnClaimedChanging(value);
					this.SendPropertyChanging();
					this._Claimed = value;
					this.SendPropertyChanged("Claimed");
					this.OnClaimedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitType", DbType="Int")]
		public System.Nullable<int> UnitType
		{
			get
			{
				return this._UnitType;
			}
			set
			{
				if ((this._UnitType != value))
				{
					this.OnUnitTypeChanging(value);
					this.SendPropertyChanging();
					this._UnitType = value;
					this.SendPropertyChanged("UnitType");
					this.OnUnitTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> LeaveId
		{
			get
			{
				return this._LeaveId;
			}
			set
			{
				if ((this._LeaveId != value))
				{
					this.OnLeaveIdChanging(value);
					this.SendPropertyChanging();
					this._LeaveId = value;
					this.SendPropertyChanged("LeaveId");
					this.OnLeaveIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectiveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EffectiveDate
		{
			get
			{
				return this._EffectiveDate;
			}
			set
			{
				if ((this._EffectiveDate != value))
				{
					this.OnEffectiveDateChanging(value);
					this.SendPropertyChanging();
					this._EffectiveDate = value;
					this.SendPropertyChanged("EffectiveDate");
					this.OnEffectiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiredDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiredDate
		{
			get
			{
				return this._ExpiredDate;
			}
			set
			{
				if ((this._ExpiredDate != value))
				{
					this.OnExpiredDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiredDate = value;
					this.SendPropertyChanged("ExpiredDate");
					this.OnExpiredDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalExpiredDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OriginalExpiredDate
		{
			get
			{
				return this._OriginalExpiredDate;
			}
			set
			{
				if ((this._OriginalExpiredDate != value))
				{
					this.OnOriginalExpiredDateChanging(value);
					this.SendPropertyChanging();
					this._OriginalExpiredDate = value;
					this.SendPropertyChanged("OriginalExpiredDate");
					this.OnOriginalExpiredDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extended", DbType="Bit")]
		public System.Nullable<bool> Extended
		{
			get
			{
				return this._Extended;
			}
			set
			{
				if ((this._Extended != value))
				{
					this.OnExtendedChanging(value);
					this.SendPropertyChanging();
					this._Extended = value;
					this.SendPropertyChanged("Extended");
					this.OnExtendedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expired", DbType="Bit")]
		public System.Nullable<bool> Expired
		{
			get
			{
				return this._Expired;
			}
			set
			{
				if ((this._Expired != value))
				{
					this.OnExpiredChanging(value);
					this.SendPropertyChanging();
					this._Expired = value;
					this.SendPropertyChanged("Expired");
					this.OnExpiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ReferenceId
		{
			get
			{
				return this._ReferenceId;
			}
			set
			{
				if ((this._ReferenceId != value))
				{
					this.OnReferenceIdChanging(value);
					this.SendPropertyChanging();
					this._ReferenceId = value;
					this.SendPropertyChanged("ReferenceId");
					this.OnReferenceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calculate", DbType="Bit")]
		public System.Nullable<bool> Calculate
		{
			get
			{
				return this._Calculate;
			}
			set
			{
				if ((this._Calculate != value))
				{
					this.OnCalculateChanging(value);
					this.SendPropertyChanging();
					this._Calculate = value;
					this.SendPropertyChanged("Calculate");
					this.OnCalculateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveCodeId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> LeaveCodeId
		{
			get
			{
				return this._LeaveCodeId;
			}
			set
			{
				if ((this._LeaveCodeId != value))
				{
					this.OnLeaveCodeIdChanging(value);
					this.SendPropertyChanging();
					this._LeaveCodeId = value;
					this.SendPropertyChanged("LeaveCodeId");
					this.OnLeaveCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveType", DbType="Int")]
		public System.Nullable<int> LeaveType
		{
			get
			{
				return this._LeaveType;
			}
			set
			{
				if ((this._LeaveType != value))
				{
					this.OnLeaveTypeChanging(value);
					this.SendPropertyChanging();
					this._LeaveType = value;
					this.SendPropertyChanged("LeaveType");
					this.OnLeaveTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_AttendanceCode]")]
	public partial class _AttendanceCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<bool> _IncludeDayOff;
		
		private System.Nullable<int> _Length;
		
		private System.Nullable<int> _DurationType;
		
		private System.Nullable<int> _AllowMinusType;
		
		private System.Nullable<decimal> _MaxMinus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnIncludeDayOffChanging(System.Nullable<bool> value);
    partial void OnIncludeDayOffChanged();
    partial void OnLengthChanging(System.Nullable<int> value);
    partial void OnLengthChanged();
    partial void OnDurationTypeChanging(System.Nullable<int> value);
    partial void OnDurationTypeChanged();
    partial void OnAllowMinusTypeChanging(System.Nullable<int> value);
    partial void OnAllowMinusTypeChanged();
    partial void OnMaxMinusChanging(System.Nullable<decimal> value);
    partial void OnMaxMinusChanged();
    #endregion
		
		public _AttendanceCode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(10)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncludeDayOff", DbType="Bit")]
		public System.Nullable<bool> IncludeDayOff
		{
			get
			{
				return this._IncludeDayOff;
			}
			set
			{
				if ((this._IncludeDayOff != value))
				{
					this.OnIncludeDayOffChanging(value);
					this.SendPropertyChanging();
					this._IncludeDayOff = value;
					this.SendPropertyChanged("IncludeDayOff");
					this.OnIncludeDayOffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Int")]
		public System.Nullable<int> Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this.OnLengthChanging(value);
					this.SendPropertyChanging();
					this._Length = value;
					this.SendPropertyChanged("Length");
					this.OnLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurationType", DbType="Int")]
		public System.Nullable<int> DurationType
		{
			get
			{
				return this._DurationType;
			}
			set
			{
				if ((this._DurationType != value))
				{
					this.OnDurationTypeChanging(value);
					this.SendPropertyChanging();
					this._DurationType = value;
					this.SendPropertyChanged("DurationType");
					this.OnDurationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowMinusType", DbType="Int")]
		public System.Nullable<int> AllowMinusType
		{
			get
			{
				return this._AllowMinusType;
			}
			set
			{
				if ((this._AllowMinusType != value))
				{
					this.OnAllowMinusTypeChanging(value);
					this.SendPropertyChanging();
					this._AllowMinusType = value;
					this.SendPropertyChanged("AllowMinusType");
					this.OnAllowMinusTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxMinus", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> MaxMinus
		{
			get
			{
				return this._MaxMinus;
			}
			set
			{
				if ((this._MaxMinus != value))
				{
					this.OnMaxMinusChanging(value);
					this.SendPropertyChanging();
					this._MaxMinus = value;
					this.SendPropertyChanged("MaxMinus");
					this.OnMaxMinusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
